"""
Navigation generator.

Creates the landing pages for all pipelines.

It never modifies mkdocs.yml or Sphinx configuration.
"""

from __future__ import annotations

from pathlib import Path

from docs.generators.utils import write_file

from .models import Pipeline


AUTO_HEADER = """<!--
AUTO-GENERATED FILE.

Generated by docs/generate_docs.py

Do not edit manually.
-->

"""


def _write(path: Path, text: str) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if path.exists():

        current = path.read_text(
            encoding="utf8",
        )

        if not current.startswith("<!--\nAUTO-GENERATED FILE."):
            return

    path.write_text(
        AUTO_HEADER + text.rstrip() + "\n",
        encoding="utf8",
    )


# ---------------------------------------------------------------------
# Root index
# ---------------------------------------------------------------------


def generate_root_index(
    docs_root: Path,
) -> None:
    """
    Generate the root Sphinx landing page.

    This page is intentionally minimal. The complete list of
    pipelines is generated in ``pipelines/index.md``.
    """

    lines = []

    lines.append("# Ensembl Genes Nextflow Pipelines")
    lines.append("")
    lines.append("Documentation for the Ensembl Nextflow pipelines.")
    lines.append("")
    lines.append(
        "The documentation is organised by pipeline. " "Each pipeline contains:"#pylint: disable=implicit-str-concat
    )
    lines.append("")
    lines.append("- Overview")
    lines.append("- Input")
    lines.append("- Output")
    lines.append("- Parameters")
    lines.append("- Modules")
    lines.append("- Workflows")
    lines.append("- Troubleshooting")
    lines.append("")
    lines.append("```{toctree}")
    lines.append(":maxdepth: 1")
    lines.append(":caption: Pipelines")
    lines.append("")
    lines.append("pipelines/index")
    lines.append("```")
    lines.append("")

    write_file(
        docs_root / "index.md",
        "\n".join(lines),
    )


def generate_navigation(
    docs_root: Path,
    pipelines: list[Pipeline],
) -> None:
    """
    Generate the pipelines index page.

    This page is used by Sphinx to build the navigation for all
    available pipelines.
    """

    lines = []

    lines.append("# Pipelines")
    lines.append("")
    lines.append("Documentation for the available Ensembl Nextflow pipelines.")
    lines.append("")
    lines.append("```{toctree}")
    lines.append(":maxdepth: 1")
    lines.append("")

    for pipeline in sorted(
        pipelines,
        key=lambda p: p.name,
    ):
        lines.append(f"{pipeline.name}/README")

    lines.append("```")
    lines.append("")

    _write(
        docs_root / "pipelines" / "index.md",
        "\n".join(lines),
    )
