"""
Navigation generator.

Creates the landing pages for all pipelines.

It never modifies mkdocs.yml or Sphinx configuration.
"""

from __future__ import annotations

from pathlib import Path

from .models import Pipeline


AUTO_HEADER = """<!--
AUTO-GENERATED FILE.

Generated by docs/generate_docs.py

Do not edit manually.
-->

"""


def _write(path: Path, text: str) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if path.exists():

        current = path.read_text(
            encoding="utf8",
        )

        if not current.startswith(
            "<!--\nAUTO-GENERATED FILE."
        ):
            return

    path.write_text(
        AUTO_HEADER + text.rstrip() + "\n",
        encoding="utf8",
    )


# ---------------------------------------------------------------------
# Root index
# ---------------------------------------------------------------------


def generate_navigation(
    docs_root: Path,
    pipelines: list[Pipeline],
) -> None:
    """
    Generate the global documentation index.
    """

    lines = []

    lines.append("# Pipelines")
    lines.append("")
    lines.append(
        "Documentation for the available Ensembl Nextflow pipelines."
    )
    lines.append("")

    lines.append("| Pipeline | Modules | Workflows | Parameters |")
    lines.append("|----------|---------|-----------|------------|")

    for pipeline in sorted(
        pipelines,
        key=lambda p: p.name,
    ):

        lines.append(
            "| "
            f"[{pipeline.title}]({pipeline.name}/index.md)"
            " | "
            f"[Modules]({pipeline.name}/modules/index.md)"
            " | "
            f"[Workflows]({pipeline.name}/workflows/index.md)"
            " | "
            f"[Parameters]({pipeline.name}/parameters.md)"
            " |"
        )

    lines.append("")

    _write(
        docs_root / "index.md",
        "\n".join(lines),
    )