#pylint: disable=duplicate-code,too-many-instance-attributes,missing-function-docstring,too-many-public-methods
"""
Workflow documentation renderer.

Generate Markdown pages describing the execution flow of a Nextflow
pipeline.
"""

from __future__ import annotations

from pathlib import Path

from .models import Pipeline
from .models import Workflow


AUTO_HEADER = """<!--
AUTO-GENERATED FILE.

Generated by docs/generate_docs.py

Do not edit manually.
-->

"""


# ---------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------


def _heading(title: str, level: int = 1) -> str:
    return "#" * level + f" {title}"


def _write(path: Path, text: str) -> None:
    """
    Write a generated file.

    Existing handwritten files are preserved.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if path.exists():

        current = path.read_text(
            encoding="utf8",
        )

        if not current.startswith("<!--\nAUTO-GENERATED FILE."):
            return

    path.write_text(
        AUTO_HEADER + text.rstrip() + "\n",
        encoding="utf8",
    )


# ---------------------------------------------------------------------
# workflow page
# ---------------------------------------------------------------------


def render_workflow(#pylint: disable=missing-function-docstring
    workflow: Workflow,
) -> str:

    lines = []

    #
    # title
    #

    lines.append(_heading(workflow.name.replace("_", " ").title()))

    lines.append("")

    if workflow.description:

        lines.append(workflow.description)

        lines.append("")

    #
    # Overview
    #

    lines.append(
        _heading(
            "Overview",
            2,
        )
    )

    lines.append("")

    lines.append(f"This workflow invokes **{len(workflow.modules)}** modules.")

    lines.append("")

    #
    # Module summary
    #

    lines.append(
        _heading(
            "Modules",
            2,
        )
    )

    lines.append("")

    lines.append("| Order | Module |")

    lines.append("|------:|--------|")

    for idx, module in enumerate(
        workflow.modules,
        start=1,
    ):

        lines.append(f"| {idx} | `{module}` |")

    lines.append("")

    #
    # Mermaid
    #

    if workflow.modules:

        lines.append(
            _heading(
                "Workflow Diagram",
                2,
            )
        )

        lines.append("")

        lines.append("```mermaid")

        lines.append("flowchart TD")

        lines.append("")

        for i, module in enumerate(workflow.modules):

            node = module.replace("-", "_").replace(".", "_")

            lines.append(f"    {node}[{module}]")

            if i:

                prev = workflow.modules[i - 1].replace("-", "_").replace(".", "_")

                lines.append(f"    {prev} --> {node}")

        lines.append("```")

        lines.append("")

    #
    # Source
    #

    lines.append(
        _heading(
            "Source",
            2,
        )
    )

    lines.append("")

    lines.append(f"`{workflow.source}`")

    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------
# pipeline
# ---------------------------------------------------------------------


def render_pipeline_workflows(
    pipeline: Pipeline,
    output_dir: Path,
) -> None:
    """
    Generate all workflow pages for one pipeline.
    """

    if not pipeline.workflows:
        return

    workflow_dir = output_dir / "workflows"

    workflow_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    #
    # Individual workflow pages
    #

    for workflow in pipeline.workflows:

        _write(
            workflow_dir / f"{workflow.name}.md",
            render_workflow(
                workflow,
            ),
        )

    #
    # workflows/index.md
    #

    lines = [
        "# Workflows",
        "",
        "Documentation for the workflows used by this pipeline.",
        "",
        "```{toctree}",
        ":maxdepth: 1",
        "",
    ]

    for workflow in sorted(
        pipeline.workflows,
        key=lambda w: w.name,
    ):
        lines.append(workflow.name)

    lines.extend(
        [
            "```",
            "",
        ]
    )

    _write(
        workflow_dir / "index.md",
        "\n".join(lines),
    )
