/*
 * GENERATE_CONFIG
 * Generate params.config file for riboseq pipeline with paths to all reference files
 */

process GENERATE_CONFIG {
    tag "${organism}_${version}"
    label 'process_low'

    container "quay.io/biocontainers/python:3.11"

    publishDir "${params.outdir}/organism_setup", mode: 'copy'

    input:
    path(star_index)
    path(bowtie_index)
    path(rrna_index)
    path(gtf)
    path(genome_fasta)
    path(chrom_sizes)
    path(ribometric_tsv)
    path(transcriptome_fasta)
    val(organism)
    val(version)

    output:
    path "riboseq_params.config",   emit: config
    path "versions.yml",            emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def base_path = "${params.outdir}/organism_setup/${organism}/${version}"
    """
#!/usr/bin/env python3

import os

# Get absolute path for the base directory
base_path = os.path.abspath("${base_path}")

config_content = f'''// Auto-generated params.config for riboseq pipeline
// Organism: ${organism}
// Version: ${version}
// Generated by: ensembl-genes-nf organism setup

params {{
    // Reference Genome Paths
    star_index = "{base_path}/${star_index}"
    bowtie_index = "{base_path}/${bowtie_index}"
    rrna_index = "{base_path}/${rrna_index}"
    gtf = "{base_path}/${gtf}"
    fasta = "{base_path}/${genome_fasta}"
    chrom_sizes_file = "{base_path}/${chrom_sizes}"
    ribometric_annotation = "{base_path}/${ribometric_tsv}"
    transcriptome_fasta = "{base_path}/${transcriptome_fasta}"

    // Organism Info
    organism = "${organism}"
    genome_version = "${version}"

    // Default Alignment Parameters (can be overridden)
    mismatches = 3
    alignment_type = "EndToEnd"
    allow_introns = true
    max_multimappers = 10
    min_mapq = 0
}}
'''

with open("riboseq_params.config", "w") as f:
    f.write(config_content)

print(f"Generated config file: riboseq_params.config")

# Write versions
with open("versions.yml", "w") as f:
    f.write('"${task.process}":\\n')
    f.write('    python: 3.10\\n')
    """

    stub:
    """
    cat > riboseq_params.config <<EOF
// Auto-generated params.config for riboseq pipeline (STUB)
// Organism: ${organism}
// Version: ${version}

params {
    star_index = "stub/star_index"
    gtf = "stub/annotation.gtf"
    fasta = "stub/genome.fa"
}
EOF

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        python: 3.10
    END_VERSIONS
    """
}
