/*
 * Build study-level count matrix from sample TSVs
 * Groups samples within a study and creates sparse matrix + vocabulary
 */

process BUILD_STUDY_MATRIX {
    tag "${study_id}"
    label 'process_medium'

    // Dependencies: python, numpy, scipy, xxhash
    // Container will be auto-generated by Wave when enabled, or use conda profile
    conda "conda-forge::python=3.11 conda-forge::numpy=1.26 conda-forge::scipy=1.12 conda-forge::xxhash-python=3.4"
    container "oras://community.wave.seqera.io/library/pip_numpy_polars_scipy_pruned:ca114eb799eb08b3"
    publishDir "${params.outdir}/studies/${study_id}", mode: 'copy'

    input:
    tuple val(study_id), val(sample_ids), path(tsv_files)

    output:
    tuple val(study_id), path("${study_id}_matrix.npz"), emit: matrix
    tuple val(study_id), path("${study_id}_vocab.pkl"), emit: vocab
    tuple val(study_id), path("${study_id}_sequences.txt.gz"), emit: sequences
    tuple val(study_id), path("${study_id}_metadata.json"), emit: metadata
    path "versions.yml", emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def sample_ids_arg = sample_ids.join(',')
    """
    build_study_matrix.py \\
        ${tsv_files} \\
        --output-dir . \\
        --study-id ${study_id} \\
        --sample-ids ${sample_ids_arg}

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        python: \$(python --version 2>&1 | sed 's/Python //')
        numpy: \$(python -c "import numpy; print(numpy.__version__)")
        scipy: \$(python -c "import scipy; print(scipy.__version__)")
    END_VERSIONS
    """

    stub:
    """
    touch ${study_id}_matrix.npz
    touch ${study_id}_vocab.pkl
    gzip -c /dev/null > ${study_id}_sequences.txt.gz
    echo '{}' > ${study_id}_metadata.json

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        python: unknown
        numpy: unknown
        scipy: unknown
    END_VERSIONS
    """
}
