flowchart TB
    subgraph " "
    v0["Channel.fromPath"]
    v4["reference"]
    v9["reference"]
    v10["annotation"]
    v15["reference"]
    v18["reference"]
    v21["reference"]
    v24["reference"]
    end
    subgraph "PANGENOME_PROJECTION [PANGENOME_PROJECTION]"
    v5(["MINIMAP2_WGA"])
    v11(["BUILD_SYNTENY"])
    v16(["PROJECT_FEATURES"])
    v19(["VALIDATE_MODELS"])
    v22(["RESCUE_PROJECTIONS"])
    v25(["REFINE_MODELS"])
    v34(["FINALISE"])
    v6(( ))
    v8(( ))
    v14(( ))
    v17(( ))
    v20(( ))
    v23(( ))
    end
    subgraph " "
    v35[" "]
    v36[" "]
    v37["stats"]
    v38["gff"]
    v41["versions"]
    end
    v1(( ))
    v0 --> v1
    v4 --> v5
    v1 --> v5
    v5 --> v6
    v5 --> v8
    v9 --> v11
    v10 --> v11
    v8 --> v11
    v11 --> v6
    v11 --> v14
    v15 --> v16
    v14 --> v16
    v16 --> v6
    v16 --> v17
    v18 --> v19
    v17 --> v19
    v19 --> v6
    v19 --> v20
    v21 --> v22
    v20 --> v22
    v22 --> v6
    v22 --> v23
    v24 --> v25
    v23 --> v25
    v25 --> v34
    v25 --> v6
    v34 --> v38
    v34 --> v37
    v34 --> v36
    v34 --> v35
    v34 --> v6
    v6 --> v41
    v1 --> v8
    v1 --> v14
    v1 --> v17
    v1 --> v20
    v1 --> v23
